<?php

declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Yireo\AdminSimpleSearchFields\ViewModel\FieldInterface;

/** @var Template $block */
/** @var FieldInterface $field */
$field = $block->getField();
$fieldValue = $block->getValue();
$fieldName = $field->getFieldName();
$modalId = $fieldName . '-search-modal';
?>
<div>
    <div class="id-preview-container">
        <div class="admin__control-addon id-preview">
            <input class="admin__control-text" type="text" id="<?= $fieldName ?>" name="<?= $fieldName ?>" placeholder="Numeric ID"
                   value="<?= $fieldValue ?>" maxLength="11"/>
            <label class="admin__addon-suffix" for="<?= $fieldName ?>" id="<?= $fieldName ?>-preview">
                <span><?= __('No data found') ?></span>
            </label>
        </div>

        <div class="button">
            <small>
                <a href="<?= $block->getUrl('simple_search/grid/product') ?>">debug</a>
                <button class="<?= $fieldName ?>-search-modal-open">Search</button>
            </small>
        </div>
    </div>

    <div id="<?= $modalId ?>" style="display:none;">
        <iframe class="simple_search"></iframe>
    </div>
</div>

<style>
    .modal-content {
        position:relative;
    }
    
    iframe.simple_search {
        width:100%;
        height:100%;
        border: 0;
        position: absolute;
        top: 10px;
        left: 10px;
        right: 10px;
        bottom: 10px;
    }
    
    .modal-content {
        height: 100%;
    }
</style>

<?= $block->getChildHtml('script') ?>